### ISSUE TITLE
spawn 启动的服务没有颜色， 需要在 env 中增加{ FORCE_COLOR: true }

### ISSUE THREAD

**Issue by amanoooo** [wallace5303/ee-core#10]
如图，麻烦确认是否是如下问题导致的， 或者有别的解决方案
![image](https://github.com/wallace5303/ee-core/assets/26034602/925adc83-5748-420b-84df-32fe06a177f9)

**Comment by amanoooo** [comment]
通过调整 bin.js 里面的args 解决了
```
args: ['.', '--env=local', '--color=always']
```

**Comment by wallace5303** [comment]
好的，这个我整理到文档中
