### ISSUE TITLE
关于SocketIO实例获取

### ISSUE THREAD

**Issue by harvest888** [wallace5303/ee-core#2]
能否支持在App上获取已经启用的SocketIo实例呢？
![image](https://user-images.githubusercontent.com/76862107/194749147-dc0b1eb0-8747-4a80-ad53-fc4a0c9f6836.png)

**Comment by wallace5303** [comment]
ee-core 2.0.0版本支持，正在整理文档

**Comment by wallace5303** [comment]
升级ee-core 2.0.3版本，
```
const Socket = require('ee-core/socket');
Socket.getSocketServer()
```
