### ISSUE TITLE
请问，这里是不是应该改成 if (!UtilsIs.macOS())

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [wallace5303/ee-core#9]
https://github.com/wallace5303/ee-core/blob/1ff7d12aa90523c2453a29019b2f700a51c1d92b/ee-core/electron/app/index.js#L30

我是小白，只是，关闭tray后，关闭所有窗口还是不会触发beforeClose，就找了好久，把这里加了个()就可以了，我是windows系统，不知道改的对不对？

**Comment by wallace5303** [comment]
对的，这个bug已经修复了
